### PR TITLE
Fix failure in listdir when server uses a locale (2.0)

### LINKED ISSUE #985: Server listdir fails with files saved during Feburary, August, and December
From downstream bug [lp:1522916](https://bugs.launchpad.net/brz/+bug/1522916), a paramiko server using a locale such as `fr_CH.UTF-8` will 'randomly' fail with `IOError: Failure` when `listdir()` is used.

To reproduce the server must have a suitable locale installed, by for instance running `sudo dpkg-reconfigure locales` on a Debian-based system. Then export the locale with the `LANG` envvar and call `setlocale(LC_ALL, '')` or similar in the server process. Finally, list a directory with files of suitable vintage. For French, the abbreviated month names 'févr.' 'août' and 'déc.' will trigger the problem.

On the server side, the following traceback is recorded:

```
Traceback (most recent call last):
  File ".../paramiko/sftp_server.py", line 111, in start_subsystem
    self._process(t, request_number, msg)
  File ".../paramiko/sftp_server.py", line 386, in _process
    self._read_folder(request_number, folder)
  File ".../paramiko/sftp_server.py", line 239, in _read_folder
    msg.add_string(attr)
  File ".../paramiko/message.py", line 273, in add_string
    s = asbytes(s)
  File ".../paramiko/common.py", line 170, in asbytes
    raise Exception('Unknown type')
Exception: Unknown type
```

Or with code is modified to allow the original exception to propagate:

```
Traceback (most recent call last):
  File ".../paramiko/sftp_server.py", line 111, in start_subsystem
    self._process(t, request_number, msg)
  File ".../paramiko/sftp_server.py", line 386, in _process
    self._read_folder(request_number, folder)
  File ".../paramiko/sftp_server.py", line 239, in _read_folder
    msg.add_string(attr)
  File ".../paramiko/message.py", line 273, in add_string
    s = asbytes(s)
  File ".../paramiko/common.py", line 168, in asbytes
    s = s.asbytes()
  File ".../paramiko/sftp_attr.py", line 223, in asbytes
    return b(str(self))
  File ".../paramiko/sftp_attr.py", line 220, in __str__
    return '%s   1 %-8d %-8d %8d %-12s %s' % (ks, uid, gid, size, datestr, filename)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb7 in position 47: ordinal not in range(128)
```

The solution is to decode the result from [`time.strftime`](https://docs.python.org/2/library/time.html#time.strftime) as the documentation suggests. For Python 3, this has already been done by the standard library so the issue does not appear. Another way to avoid the issue is using a language neutral locale like `C.UTF-8`.

### PR DESCRIPTION
**Pull request by bz2**
Fixes #985

SFTPAttributes uses the locale-aware %b directive for the
abbreviated month name with time.strftime, but was not
decoding the result on Python 2.7.

Add a strftime alias in py3compat that will always return
unicode, and resolve the mixing of bytes and text in
SFTPAttributes methods.

Add a test at the listdir level, and a more specific test
for the SFTPAttributes asbytes method.

### CODE REVIEW

**Comment by bz2** [comment]
Travis on pypy failed hard on an untouched test:

```
test_2_big_file (tests.test_sftp_big.BigSFTPTest) ... ........ 7s 

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

Perhaps it's right to remove the pypy target from `.travis.yml` for this series?

**Comment by ploxiln** [comment]
It's an intermittent failure, a re-test is likely to pass. With an updated pypy it might be more reliable. Travis-CI hasn't updated the available versions of pypy in quite a while, unfortunately ...

**Comment by bitprophet** [comment]
Confirm, pypy sometimes times out on Travis, it's unfortunate but hard to avoid. Typically if everything-but-pypy passes you're gtg.

**Comment by bz2** [comment]
Is there anything I can do to help you with the landing/release process?

**Comment by jelmer** [comment]
Any news on this?

**Comment by bitprophet** [comment]
Rebased this into latest 2.x stable line; it's now out as part of 2.8.1. Thanks!

**Pull request closed without merging**
