### PR TITLE
Support for new OpenSSH 6.5+ private key format 

### PR DESCRIPTION
**Pull request by mchlt**
Added support for new OpenSSH 6.5+ private key format. See issue #602.
This code only adds the ability to READ that key format, not write it.

I could only test the keys on one box as I found that my Solaris, Raspberry pi and Oracle Linux boxes all still have older versions of SSH. So only tested this on Ubuntu 15 against OpenSSH_6.9p1.

Figuring out the actual format and which blob was which key was quite the puzzle, it's not really documented completely anywhere.

As discussed previously, this does add a dependency on py-bcrypt 0.4
The cryptography module does not have bcrypt, nor the required bcrypt_pbkdf function (which is similar, but not quite the same as pbkdf2...)

### CODE REVIEW

**Comment by cjac** [comment]
Have you, in your wanderings through this code, found a way to identify the Public Key Algorithm of a given private key file?  Or even the content of that file would work.

**Comment by XVilka** [comment]
Should be rebased, I think. Any chance to get this merged?

**Comment by XVilka** [comment]
Should be closed since superseded by https://github.com/paramiko/paramiko/pull/1343

**Comment by bitprophet** [comment]
Rolling into #1343 as noted.

**Pull request closed without merging**
