### PR TITLE
Close socket on failure

### LINKED ISSUE #1126: Unclosed socket on connection failure
With Python 3.6.3 and Paramiko 2.4.0, connecting with an invalid *host* or *port* causes a `ResourceWarning` (noticeable when the interpreter warnings are activated with the `-Wall` flag) as the underlying socket is not closed in such a case:

Input (example with an invalid port):

```bash
$ python3 -Wall <<EOF
import paramiko
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy)
with client.connect(hostname="localhost", port=0): pass
EOF
```

Output:

> /home/master/.local/lib/python3.6/site-packages/paramiko/client.py:332: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::', 49626, 0, 0)>
>   sock = socket.socket(af, socket.SOCK_STREAM)
> /usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
>   import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
> Traceback (most recent call last):
>   File "<stdin>", line 4, in <module>
>   File "/home/master/.local/lib/python3.6/site-packages/paramiko/client.py", line 357, in connect
>     raise NoValidConnectionsError(errors)
> paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 0 on 127.0.0.1 or ::1
> sys:1: ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 58766)>

### PR DESCRIPTION
**Pull request by YoavCohen**
As mentioned in socket docs:
"Sockets are automatically closed when they are garbage-collected, but it is recommended to close() them explicitly, or to use a with statement around them."

Resolve #1126

### CODE REVIEW

**Comment by MrMino** [comment]
Does every `socket.error` signify a failure that would require `socket.close()`? Were custom sockets taken into consideration?

**Comment by YoavCohen** [comment]
> Does every `socket.error` signify a failure that would require `socket.close()`? Were custom sockets taken into consideration?

all this code runs under a condition the sock wasn't provided, so it muse be a socket create be the connect function so are responsible for cleanup.

The scenario I encounter was when when errno=EHOSTUNREACH but sock.close() looks enough safe to call on any on every socket.error.
thoughts?

**Comment by dominiclondon** [comment]
What's the status of this?

**Comment by bskinn** [comment]
@dominiclondon It's been idle, with other paramiko/fabric/invoke matters taking higher priority in bitprophet's weekly OSS allotment. Thanks for bumping it to indicate your interest in it, I've now triaged it.

**Comment by bitprophet** [comment]
Thanks all. Merged this and wrote a quick test for it (😩). Does look like a lot of the other related tickets @bskinn dug up (👍🏻✨) aren't completely solved by this, but it'll still help with a subset for sure. Closed the one other that seemed like a full-on duplicate.

**Comment by bitprophet** [comment]
Thanks all. Merged this and wrote a quick test for it (😩). Does look like a lot of the other related tickets @bskinn dug up (👍🏻✨) aren't completely solved by this, but it'll still help with a subset for sure. Closed the one other that seemed like a full-on duplicate.

**Pull request closed without merging**
