### PR TITLE
Drop support for RC4.

### PR DESCRIPTION
**Pull request by alex**
It's cryptoanalytically completely 100% broken, and practical attacks have been demonstrated against it's usage in TLS.

As far as I'm aware, there's no use case for RC4 based on compatibility.

### CODE REVIEW

**Comment by alex** [comment]
Test failure unrelated, known flakey.

**Comment by alex** [comment]
@bitprophet This is green now, nice work fixing that flakey bug!

**Comment by bitprophet** [comment]
Thinking 2.0 for this too (meaning I'll merge it same time as #394) unless you can think of a great reason to put it in 1.17. Not like someone's gonna roll up to 1.17 all "oh hey this still supports ARC4, gonna use that for this new code here!".

**Comment by bitprophet** [comment]
Also oh god is it a feature, bug or support? it could be all 3!! `#maintainerproblems`

P.S., thanks for this :) Love deleting stuff.

**Comment by alex** [comment]
I've abandoned the existential task of categorizing security improvements
as bugs or features :-)

On Sun, Apr 24, 2016 at 6:39 PM, Jeff Forcier <notifications@github.com>
wrote:

> Also oh god is it a feature, bug or support? it could be all 3!!
> #maintainerproblems
>
> P.S., thanks for this :) Love deleting stuff.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/paramiko/paramiko/pull/667#issuecomment-214055152>
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: D1B3 ADC0 E023 8CA6

**Comment by bitprophet** [comment]
Honestly, that strikes me as an argument for expanding the categorizations so there's just one for 'security'. Sadly bugs are already colored red in my setups...maybe I'll bring back `<blink>`...

**Comment by bitprophet** [comment]
Feels silly to make this 2.0 and the md5 stuff 3.0, let's call this 3.0 instead.

**Comment by alex** [comment]
The report in #923 is correct, the RC4 code looks broken. To me that's an argument for removing it now, since it's both broken (which no one seems to mind) and insecure.

**Comment by bitprophet** [comment]
For reference, the original code adding arcfour/RC4 appears to have been [this commit](https://github.com/paramiko/paramiko/commit/ac42ba88d70ec0cc6acc1b1d5526591de5d1eae2) from 2009.

Seems moot tho re: the previous note about RC4 being broken at least as of our 2.0 release. If it did work back in the 1.x line, then this just falls under the increasingly large category of "if you can't get with modern crypto, just use the hey-it-still-works-fine 1.x releases". If it didn't, then...100% meh!

**Comment by alex** [comment]
@bitprophet it was broken when I migrated it to cryptography: https://github.com/paramiko/paramiko/commit/56a4739923a356ff5670b4620139ca55a2f30148#diff-15fec8ffdb11118d0c724574145b99b5R1562 should be `.update()`

**Comment by bitprophet** [comment]
Moved to 2.0 cuz it's been broken since 2.0 and removing the feature outright is clearly the pro-est bugfix. Thanks again Alex!

**Pull request merged**
