### PR TITLE
Add GSS-API support for using the 'gssapi' package (in addition to older 'python-gssapi')

### PR DESCRIPTION
**Pull request by akruis**
I rebased pull request #861 for 2.2. Additionally I improved backwards compatibility a bit (keep the internal name of the old python-gssapi class).

This pull request could be applied to 2.3 too.
@SebastianDeiss: please review this pull request.

### CODE REVIEW

**Comment by SebastianDeiss** [comment]
@akruis: LGTM.

**Comment by sscherfke** [comment]
When will this be merged and released?

**Comment by sscherfke** [comment]
@bitprophet Can I help you with anything to get this patch merged?

**Comment by akruis** [comment]
An updated version of this pull request is available as #1311.

**Pull request closed without merging**
