### PR TITLE
add missing file-like object methods

### PR DESCRIPTION
**Pull request by ameily**
The Python `io` module requires that file-like objects implement a specific API. For paramiko, four methods were missing: `readable()`, `writable()`, `seekable()`, and `readinto()`.

### Test

The following Python3 code can be run to test that this Pull Request implements the missing file-like object methods. An exception will be raised without this Pull Request applied. Here, `s` is an `SSHClient` instance.

```python
sftp = s.open_sftp()
raw = sftp.open("/path/to/a/text/file.txt", "r")
wrapper = io.TextIOWrapper(raw, encoding='utf-8')

data = wrapper.read(10)
wrapper.seek(0)
data2 = wrapper.read(10)
```

### CODE REVIEW

**Comment by ameily** [comment]
Is there anything I have to do on my end to get this PR merged?

**Comment by bitprophet** [comment]
It looks like there's merge conflicts - keeping a PR branch up to date with master is definitely a good idea! (But you can ignore Travis status for now, there is a race condition it's triggering that needs fixing.)

I also notice I did not add to a milestone, just did so. Thanks for your patience!

**Comment by ameily** [comment]
I merged upstream master

**Comment by bitprophet** [comment]
Thanks @ameily! Figured I'd review and merge while I was lookin :)

For the future, some notes, please:

* Try not to include whitespace changes, they make the diff longer & pollute git-blame ;)
* No need for `:meth:` in front of method name references, Sphinx's default role stuff tends to work as-is and it's our style to rely on that.
* The changelog needs issue links & class/method links when possible - just refer to how nearby line-items do it for a reference.

**Comment by ameily** [comment]
Awesome! Thanks for the heads up.

**Pull request merged**
