### PR TITLE
Use pytest.mark.xfail instead of broken pytest_relaxed

### PR DESCRIPTION
**Pull request by mimi1vx**
pytest_relaxed is broken with newer versions on pytest. And pytest itself has needed funcionality

### CODE REVIEW

**Comment by mimi1vx** [comment]
@alex  travis fail looks like wrong setup for python 3.4

**Comment by mimi1vx** [comment]
@bitprophet btw. I have teste paramiko with pytest-4.5.x and all PASS :D

**Comment by bitprophet** [comment]
I was hoping to eventually migrate the tests to use pytest-relaxed's style of organization, so I'd rather go fix that to work with newer pytest instead (https://github.com/bitprophet/pytest-relaxed/issues/2). Thanks though! Gonna go poke that now because why not.

**Comment by bitprophet** [comment]
Got that sorted, pytest-relaxed 1.1.5 is here and with it the latest pytest. Hope this is good on your end too after the update 👍

**Pull request closed without merging**
