### PR TITLE
Improve __hash__ functions

### PR DESCRIPTION
**Pull request by franciscouzo**

### CODE REVIEW

**Comment by bitprophet** [comment]
Can you clue me in to _how_ this is an improvement? Context-less PRs are no fun :) thanks!

**Comment by ploxiln** [comment]
Less code and "interesting" logic (multiply by 37) in these implementations, while still incorporating all the same class member data into the hash. And I think tuple hash performance is about as good as you'll get by any other strategy.

(Different hash result than before, but that's fine because it just needs to be consistent within the process.)

**Comment by bitprophet** [comment]
Less code is usually good, I just wish I understood why this "multiply by 37" behavior was added in the first place.

**Comment by SethMichaelLarson** [comment]
Good arbitrary prime number for combining hash values?

**Comment by SethMichaelLarson** [comment]
Also smallest prime greater than 32.

**Comment by ploxiln** [comment]
Compare to the very simple "djb2" hash function http://www.cse.yorku.ca/~oz/hash.html

```c
    unsigned long
    hash(unsigned char *str)
    {
        unsigned long hash = 5381;
        int c;

        while (c = *str++)
            hash = ((hash << 5) + hash) + c; /* hash * 33 + c */

        return hash;
    }
```

So you see, "hash * CONST_INT + next_input" is a common simple hash strategy (hash is expected to overflow).

**Pull request merged**
