### PR TITLE
Fixed "Bad file descriptor", "Broken pipe" and another kind of error…

### PR DESCRIPTION
**Pull request by qualab**
Fixed "Bad file descriptor", "Broken pipe" and another kind of errors on multithreading usage of PosixPipe when we've got close() and set() at the same time. In such case check for self._closed is invalid and not synchronized with close() method called from separated thread.

### CODE REVIEW

**Comment by qualab** [comment]
Seems tests.test_transport.TransportTest should have greater timeout or it is unstable.

**Comment by bitprophet** [comment]
See #691 for more info.

**Comment by whbos** [comment]
We've been running into the same errors. Will this code be committed?

**Comment by tsellers-r7** [comment]
We are seeing similar.  Is there something we can do to help get this fix or a version of it into production?

**Comment by bitprophet** [comment]
Adding to a release milestone.

I'll admit that changes like this make me nervous, the project has a history of back & forths on this type of code, basically bug whack-a-mole where it fixes one set of issues but creates (or regresses, often) into another.

That said, this basically just looks like "rub some locking on it" so it's better than similar changes that are just shuffling `close` calls around and suchlike.

If y'all want to make this an even easier merge, and can come up with a new test for the test suite that catches the bug this fixes, that'd be awesome. Not required, however.

**Comment by qualab** [comment]
Actually there is a very hard way to reproduce this. System must run many threads which are asynchronously do via SSH short but recent actions using paramiko. There is recent bug but in case of system mix close() and set() recent enough for race on socket descriptor (start set() due close() running). I found that only using strace, there was one of the most hard bugs I ever found.
But it used in tests of Parallels Automation (platform for Parallels Plesk, now renamed to Odin) with that fix and never fire after that without any slow down of test run.

**Comment by rafaelthca** [comment]
I've ran into the same issue. I am the developer of https://github.com/OmniDB/OmniDB, a python web based database management tool.

OmniDB instantiates several threads to perform database operations concurrently. These threads access the database directly or via SSH tunnels (created with paramiko). I was experiencing the same issue (bad descriptor) and @qualab's PR fixed it.

I'll try to come up with a test code that generates this issue.

**Comment by stromnet** [comment]
I'm having the same issues. I have tested both this fix and the one proposed in #1158, both works.

I'll keep my details in #1157 as that one is open.

**Pull request closed without merging**
