### PR TITLE
travis-ci: update pypy test run

### PR DESCRIPTION
**Pull request by ploxiln**
I found the magic incantation to get the full list of available python/pypy versions:
https://github.com/travis-ci/travis-ci/issues/6727#issuecomment-307186234

Hopefully this is faster and more reliable ...

### CODE REVIEW

**Comment by ploxiln** [comment]
pypy2.7-5.8.0 was missing a virtualenv folder that's present in the other travis-ci python tarballs, trying another one

**Comment by ploxiln** [comment]
Travis-CI's pypy tarballs are prepared rather sloppily, practically every one has a different problem. No matter, I can try them all...

**Comment by ploxiln** [comment]
"pypy-5.6.0" worked. Maybe this will be more reliable.

**Comment by bitprophet** [comment]
Neat, didn't realize they had a wider spread now. Thanks!

**Pull request merged**
