### PR TITLE
Add support for PyCryptodome (and PyPy)

### PR DESCRIPTION
**Pull request by Legrandin**
This patch makes paramiko work with PyCryptodome in addition to PyCrypto.
With the former, paramiko can run under PyPy.

### CODE REVIEW

**Comment by bitprophet** [comment]
Thanks for this. I have gut-feeling-only concerns about some of the changes (mostly the ones in `rsakey.py`) and as mentioned in #637 I'm hoping to largely obviate the issue by merging cryptography.io support for 2.0. (That's another minor/moderate concern - how well those two PRs interact, should we merge both in either order.)

So for now I'll leave this open & attach to a new "post-2.0 1.x feature release" milestone so that when I re-examine the state of 1.x vs 2.x, it's on deck. Thanks again!

**Comment by alex** [comment]
@bitprophet if you plan to merge the cryptography.io patch, I'd say there's no reason to land this, it's 100% code that my PR removes/replaces.

**Comment by bitprophet** [comment]
@alex Good to have that confirmed (if you see the earlier notes / the other ticket, I was kinda hoping it would be the case)! Thanks :)

**Comment by blackwind** [comment]
It's great that cryptography.io is coming, but the PR for it has been open for a year and a half and counting, and in the interim, using paramiko on Windows is FAR more difficult than it needs to be. Any chance you'd reconsider merging this as a stopgap?

**Pull request closed without merging**
