### PR TITLE
log_to_file() should append instead of replace

### PR DESCRIPTION
**Pull request by ploxiln**
easy fix for #683 

in fairness, this was written in 2004 for demo/test code ...

### CODE REVIEW

**Comment by bitprophet** [comment]
Why doesn't github's "change base" feature _ever_ work the way I want it to 😭  I'll just cherry-pick these. Thanks!

**Comment by ploxiln** [comment]
"change base" to an "older" branch will end up including commits that are on the newer branch already but not the older branch. The pull-request branch has to be updated as well. (I'm happy to do that by the way, I'll cherry-pick to 1.18 and push up here.)

**Comment by bitprophet** [comment]
Already did it, but thanks anyway. And yea, I just...you know...wish github would do the rebasing for us. Otherwise I'm not entirely clear on how useful the feature is.

**Comment by bitprophet** [comment]
Cherry-picked to 1.18, 2.0, 2.1, master.

**Comment by ploxiln** [comment]
sounds good

**Pull request closed without merging**
