### PR TITLE
kex: support curve25519-sha256@libssh.org

### LINKED ISSUE #532: weakdh.org: Doesn't work with "KexAlgorithms curve25519-sha256@libssh.org"
As suggested here: https://weakdh.org/sysadmin.html on the new weakdh.org attack site, one solution is to use:

```
KexAlgorithms curve25519-sha256@libssh.org
```

On the sshd_config of the server. So that lines restricts the KexAlgorithms to just that one. But that makes paramiko unable to connect.

It throws this error:

```
No handlers could be found for logger "paramiko.transport"

Fatal error: Incompatible ssh peer (no acceptable kex algorithm)

Underlying exception:
    Incompatible ssh peer (no acceptable kex algorithm)
```

I'm using paramiko==1.15.2 (the last release). Can you please consider fixing this ?

### PR DESCRIPTION
**Pull request by fuhry**
This commit introduces support for the `curve25519-sha256@libssh.org` key exchange method, which is the currently (August 2018) recommended method for all modern SSH servers and clients.

Client mode, server mode and unit tests are included and have been tested with the OpenSSH client and server.

Closes #532

### CODE REVIEW

**Comment by fuhry** [comment]
I've got the build passing on everything except PyPy 5.6.0, and that's not something I have a lot of expertise in. Could use some help from someone who knows PyPy.

The build log suggests that this might actually be caused by an outdated version of OpenSSL. This seems to be confirmed by @reaperhulk's comment on pyca/cryptography#3859, so maybe this is an environment issue.

My implementation is pretty straightforward as it just sits on top of the pyca-cryptography x25519 primitives API, but I'd welcome reviews from anyone with crypto knowledge (particularly more EC knowledge than me) to validate it anyway.

@bitprophet - would appreciate a cursory glance over this when you have a moment. I'd also welcome any suggestions you have for fixing the PyPy 5.6.0 build. This will greatly improve the security of paramiko so it would be really nice to get it included. Thanks!

**Comment by fuhry** [comment]
FYI: I've merged #1232 into this PR to attempt to fix the PyPy issues... will back that change out if it doesn't work.

**Comment by fuhry** [comment]
For anyone who would like an unofficial build with both curve25519 and @edgsousa's EtM patch, I've put those together into a branch here: https://github.com/fuhry/paramiko/tree/curve25519%2Betm

**Comment by reaperhulk** [comment]
PyPy has no stable ABI so we can't ship wheels for it on PyPI. This means that it will build against system OpenSSL, which will be 1.0.1 on trusty (which the Travis builders are currently using). I'd suggest writing something to do capability detection for x25519 and skip the tests if unsupported.

**Comment by fuhry** [comment]
@reaperhulk Thanks for the advice - I implemented your suggestion and this is working nicely. 

Builds are now passing.

**Comment by mboersma** [comment]
Could this get merged soon? With a recent Ubuntu security update, ssh access with `paramiko` is broken for all new VMs our service is creating in Azure. This would fix it.

**Comment by crawfxrd** [comment]
Using this produces a deprecation notice from `cryptography`.
```
/root/.local/share/virtualenvs/system-2ifbupYJ/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/x25519.py:35: CryptographyDeprecationWarning: public_bytes now requires encoding and format arguments. Support for calling without arguments will be removed in cryptography 2.7
```

**Comment by fuhry** [comment]
@crawfxrd Latest commit should resolve that deprecation notice.

**Comment by Conan-Kudo** [comment]
This latest change addresses remaining issue I had noted earlier.

**Comment by mikeln** [comment]
Really could use this PR merged.   Dealing with a number of servers that only support this kex algorithm.

**Comment by sylr** [comment]
I'd also really need this PR to be merged if the implementation is all right.

**Comment by sylr** [comment]
cc @bitprophet @reaperhulk

**Comment by reaperhulk** [comment]
I would love for this PR to get merged, but have no access to this repository.

**Comment by swills** [comment]
Another vote to merge this, and hopefully include in the next release.

**Comment by fuhry** [comment]
Note - @ploxiln had some good suggestions in the paramiko-ng PR which has since been merged (ploxiln/paramiko-ng#18) and improved somewhat (ploxiln/paramiko-ng#19). I'm incorporating those changes into this PR.

**Comment by fuhry** [comment]
@bitprophet @reaperhulk This is once again ready to go; please let me know if you would like it squashed (5 commits currently).

**Comment by bitprophet** [comment]
I Frankenstein'd Alex's slightly tidier implementation with your tests (&, as it turns out, your on-spec use of the otherwise undocumented `hash_algo` attribute! 😬✌️) so this is good to go now. Thanks!

**Pull request closed without merging**
