### PR TITLE
Support for group14, group16 Kex and HMAC EtM

### PR DESCRIPTION
**Pull request by edgsousa**
Hi

Some devices I work with were upgraded to a ssh config that only allows kex group14-sha256. Also I saw the request #1229, and decided to implement that as well.

### CODE REVIEW

**Comment by fuhry** [comment]
For anyone who would like an unofficial build with both curve25519 and @edgsousa's EtM patch, I've put those together into a branch here: https://github.com/fuhry/paramiko/tree/curve25519%2Betm

**Comment by mikeln** [comment]
LGTM and it appears to fix several of my issues with SSH to Azure nodes.

**Comment by mikeln** [comment]
How do we get this PR reviewed , merged, and added to a release?  I.e. who is the person we need to bother?

**Comment by ploxiln** [comment]
for what it's worth, I've started a fork, merged this and a few other things according to my own taste, and made an initial release: https://github.com/ploxiln/paramiko-ng/releases/tag/2.5.0

**Comment by bitprophet** [comment]
Merged to latest master, cleaned up some code a bit, fixed a copyright header (I hate you, LGPL) and added a changelog. Then tested against OpenSSH and both new MACs and both new kexen seem to work great. Thanks!

**Pull request merged**
