### PR TITLE
fix for list index out of range, breaking vorta

### LINKED ISSUE #1637: pkey.py _read_private_key: list index out of range (core dumped)
to recreate bug:
````
pip install vorta
rm ~/.ssh/.known_hosts.lock
touch ~/.ssh/.known_hosts.lock
vorta -f

Traceback (most recent call last):
File "/opt/anaconda/anaconda3/bin/vorta", line 10, in
sys.exit(main())
File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/vorta/main.py", line 40, in main
app = VortaApp(sys.argv, single_app=True)
File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/vorta/application.py", line 59, in init
self.open_main_window_action()
File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/vorta/application.py", line 80, in open_main_window_action
self.main_window = MainWindow(self)
File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/vorta/views/main_window.py", line 37, in init
self.repoTab = RepoTab(self.repoTabSlot)
File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/vorta/views/repo_tab.py", line 55, in init
self.init_ssh()
File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/vorta/views/repo_tab.py", line 88, in init_ssh
keys = get_private_keys()
File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/vorta/utils.py", line 74, in get_private_keys
parsed_key = key_format.from_private_key_file(key_file)
File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/paramiko/pkey.py", line 235, in from_private_key_file
key = cls(filename=filename, password=password)
File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/paramiko/rsakey.py", line 55, in init
self._from_private_key_file(filename, password)
File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/paramiko/rsakey.py", line 175, in _from_private_key_file
data = self._read_private_key_file("RSA", filename, password)
File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/paramiko/pkey.py", line 308, in _read_private_key_file
data = self._read_private_key(tag, f, password)
File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/paramiko/pkey.py", line 320, in _read_private_key
m = self.BEGIN_TAG.match(lines[start])
IndexError: list index out of range
Segmentation fault (core dumped)
````

### PR DESCRIPTION
**Pull request by poleguy**
to recreate bug:
````
pip install vorta
rm ~/.ssh/.known_hosts.lock
touch ~/.ssh/.known_hosts.lock
vorta -f

Traceback (most recent call last):
  File "/opt/anaconda/anaconda3/bin/vorta", line 10, in <module>
    sys.exit(main())
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/vorta/__main__.py", line 40, in main
    app = VortaApp(sys.argv, single_app=True)
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/vorta/application.py", line 59, in __init__
    self.open_main_window_action()
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/vorta/application.py", line 80, in open_main_window_action
    self.main_window = MainWindow(self)
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/vorta/views/main_window.py", line 37, in __init__
    self.repoTab = RepoTab(self.repoTabSlot)
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/vorta/views/repo_tab.py", line 55, in __init__
    self.init_ssh()
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/vorta/views/repo_tab.py", line 88, in init_ssh
    keys = get_private_keys()
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/vorta/utils.py", line 74, in get_private_keys
    parsed_key = key_format.from_private_key_file(key_file)
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/paramiko/pkey.py", line 235, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/paramiko/rsakey.py", line 55, in __init__
    self._from_private_key_file(filename, password)
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/paramiko/rsakey.py", line 175, in _from_private_key_file
    data = self._read_private_key_file("RSA", filename, password)
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/paramiko/pkey.py", line 308, in _read_private_key_file
    data = self._read_private_key(tag, f, password)
  File "/opt/anaconda/anaconda3/lib/python3.6/site-packages/paramiko/pkey.py", line 320, in _read_private_key
    m = self.BEGIN_TAG.match(lines[start])
IndexError: list index out of range
Segmentation fault (core dumped)
````

resolves #1637

### CODE REVIEW

**Comment by damiansf** [comment]
👍

**Comment by poleguy** [comment]
Hmmm... I'm new here. How do I get the attention of someone to get this merged? I'll try requesting a review from one of the three people listed. If that's not the right process, I apologize.

**Comment by poleguy** [comment]
Please see new bug request I just created related to this. #1637 
This is a proposed fix for that bug.

**Comment by jochenparm** [comment]
Hey, I'm also experiencing this problem. Could you please accept this PR or give some feedback on why you're not including it in a release?

**Comment by poleguy** [comment]
This seems to have fallen through the cracks. I tried to get @lndbrg to review, but no response. Maybe he's filtered his messages, and isn't seeing this?

I see no way of adding a different reviewer.
I see no way to link this to the bug report. #1637 

This is my first contribution to an open source repository. So far it seems to not work the way I had hoped. Oh well.

**Comment by poleguy** [comment]
@bitprophet This is a simple bug fix that would be a quick merge. I see now that it does affect others, not just me, so I thought I'd reach out as I see you've done recent merges and are prioritizing bug fixes (via your status.).

I don't see any paramiko specific instructions on how to get this noticed, included, etc. Is there something I missed?

It may be impolite to draw your attention to it by calling out your name. I'm new to github and PR's, and think I did some wrong things in setting this up. I think I added @lndbrg as a reviewer to this, and that may have been inappropriate. I also entered the PR before the bug report. I can't seem to link them, etc.

**Comment by ploxiln** [comment]
This is mostly a fine submission. Some tips:
  * don't put `resolves #1637` in the title, put it in the description, it will link correctly there
  * don't use your master branch, create a feature branch, so that you can easily create more pull requests in parallel
  * in your description on github, or in comments, use [fenced code blocks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) to make terminal output (including tracebacks) and code samples more readable

The main problem here is that this repo is not well maintained currently. Take a look at the open pull requests, yours is not the only kinda-important simple bug fix which has been sitting for a long time. No one really wants to say it out loud, including me, because it's a bit rude. The maintainer has no obligations to this free volunteer effort, and lots of nagging from all over can stretch their time and attention even thinner. But it is useful to recognize the reality of the situation and look elsewhere. On the upside, this is fully open source, so you can fix and use your own fork without limitation. That's what I've done ...

**Comment by poleguy** [comment]
@ploxiln Thank you for the tips. I'm sorry to take your time, but I appreciate the help in understanding the lay-of-the-land as a newcomer. I will take your tips to heart; they make sense and I follow them in the future.

Thank you also for your honesty and willingness to say the truth without cover. As that is the lay of the land, I will work around this bug, fork, etc. I will leave this PR open in case the situation eventually catches up. 

I have read about the open-source problems of the nagging users and the lack of mechanisms to get funding, etc. I now am one of those nagging users. oops. I won't comment on this again, as I mean to be part of the solution, not the problem.

Signing off...

**Comment by CloudZazu** [comment]
I'm hitting into this issue as well

**Review by uea — APPROVED** [review]

**Comment by bskinn** [comment]
@poleguy, apologies for the long silence on this. We're working slowly through the backlog of issues/PRs (mostly as people post on old items and they become fresh again,,,,). The PR seems pretty straightforward.

If you're still interested in this PR, can I ask--what is the value in changing the exception that's thrown? Clearly, it's a more relevant exception and clarifies what went wrong. Is there some specific value to/meaning for vorta to raising an `SSHException`?

**Comment by poleguy** [comment]
I don't think there is any particular value/meaning to using SSHException. I'm not an expert on exceptions, and I don't recall why I picked that one exactly, except that I would see the message and it would be specific. 
Thinking about it now, it seems that the best thing to do would be to just handle the "empty file" case by doing nothing rather than raising an error at all.

**Comment by ploxiln** [comment]
`SSHException` is the (parent) class used by all exceptions raised within _paramiko_. There are some places, for example in the paramiko SSHClient, where `SSHException` is caught and handled, but other exceptions are not caught and cause the whole thing to fail inappropriately (instead of continuing on to try the next key candidate):

https://github.com/paramiko/paramiko/blob/50d33223f9ec9e308a3fda519b36f78be859c4bc/paramiko/client.py#L734-L749

Maybe vorta is doing something similar, I dunno.

**Comment by bitprophet** [comment]
Thanks all. Cherry-picked this back to 2.9 and up, added tests/changelog. It'll go out in the next release(s).

**Pull request closed without merging**
