### PR TITLE
test with pypy on Travis CI

### PR DESCRIPTION
**Pull request by ploxiln**
and remove tox config
as suggested in https://github.com/paramiko/paramiko/pull/838#issuecomment-257656945

(we'll see how it goes ...)

### CODE REVIEW

**Comment by ploxiln** [comment]
still trying to find a version of pypy3 that will work ;)

**Comment by ploxiln** [comment]
I gave up on finding a new-enough version of pypy3 available on Travis CI. Anyway, this passes tests now with pypy2.7-5.4.1 added to the testing matrix.

**Comment by bitprophet** [comment]
Yup, last time I looked at a PyPy related issue (was only a number of weeks ago, probably over on pyinvoke/invoke), it needed PyPy3+ to truly be considered fixed, and Travis didn't have that yet. So we're kinda waiting on that before we can be super happy.

Sounds like you got tests working on a good-enough PyPy version anyways tho. thanks!

**Comment by bitprophet** [comment]
Cherry-picked back to 1.17+.

**Pull request closed without merging**
