### PR TITLE
Don't pass IV to pycrypto when using MODE_CTR

### LINKED ISSUE #713: Paramiko passes IV to pycrypto when using MODE_CTR
In later versions of pycrypto, this throws an exception, because of this commit:
https://github.com/dlitz/pycrypto/commit/8dbe0dc3eea5c689d4f76b37b93fe216cf1f00d4

### PR DESCRIPTION
**Pull request by jmh045000**
- Fixes #713

### CODE REVIEW

**Comment by bitprophet** [comment]
What's the impact of this on *older* versions of PyCrypto? (Paramiko 1.x supports PyCrypto 2.1 and up, basically.)

From a skim, it seems like "probably nothing?" because the commit linked in #713 states that the IV was already being ignored; but it'd be nice to make sure we're not risking errors for folks on PyCrypto 2.1-2.5 or so.

**Comment by bitprophet** [comment]
Double checked this change & the referenced PyCrypto commit and I'm still kinda uncomfortable just-merging this. Help me out, @jmh045000?

- What's a concrete example of the bug/exception/etc this causes?
- What PyCrypto version or versions does it impact?
- What happens if you run Paramiko on an older PyCrypto with this change in place?
- Is there a non crummy way to introspect whether to pass in `iv` vs `""`? (Which would then mean the questions about PyCrypto version become moot.)

I'd dig more myself but given 2.0+ no longer use PyCrypto I can't afford the time :) if you get back to me, happy to keep it rolling! Thanks!

**Comment by mimi1vx** [comment]
https://bugzilla.suse.com/show_bug.cgi?id=1020340

**Comment by nvgoldin** [comment]
Hitting the same issue on fedora 24 - around a week ago python2-crypto RPM was upgraded in fedora24/updates to python2-crypto.x86_64 2.6.1-13.fc24. This essentially breaks paramiko on fedora24, as v2.x RPMs are not available there. The only option is to pin down an older version of python2-crypto, but as this is a security issue, its by far not the best solution.

https://bugzilla.redhat.com/show_bug.cgi?id=1418084

**Comment by jmh045000** [comment]
I plan on resolving the concerns @bitprophet has this week.  Then I'll resolve the merge conflicts and hopefully it will go in.

**Comment by nvgoldin** [comment]
Just updating the same python2-crypto version just hit EPEL, so it is going to affect all el7 installations. The older versions were removed, so you can't pin down the version either.
On fedora24 - looks like paramiko v2.x is going to be pushed to updates soon. 

epel - https://bugzilla.redhat.com/show_bug.cgi?id=1419312
fc24 - https://bodhi.fedoraproject.org/updates/FEDORA-2017-6bf7d0c531

**Comment by jmh045000** [comment]
My testing script:
```
#!/bin/bash

rm -rf test
mkdir test
cd test

cat > paramiko_test.py << EOF
#!/usr/bin/env python2
import paramiko
import sys
try:
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect('<redacted>', username='pycrypto-test', password='test')
    _, stdout, _ = ssh.exec_command('uptime')
    print '\n'.join(stdout.readlines()).strip()
    sys.exit(0)
except Exception as e:
    print e
    sys.exit(1)
EOF
chmod +x paramiko_test.py

test_exec=$(readlink -m paramiko_test.py)

git clone https://github.com/dlitz/pycrypto.git &>/dev/null
git clone https://github.com/jmh045000/paramiko.git &>/dev/null
(cd paramiko ; git remote add upstream https://github.com/paramiko/paramiko.git ; git fetch upstream) &>/dev/null

pycrypto_dir=$(readlink -m pycrypto)
paramiko_dir=$(readlink -m paramiko)

for pycrypto_version in v2.1.0 v2.2 v2.3 v2.4.1 v2.5 v2.6 v2.6.1 master ; do
    for paramiko_version in v1.17.3 v1.18.1 ; do
        working_dir=pycrypto_${pycrypto_version}-paramiko_${paramiko_version}
        virtualenv $working_dir &>/dev/null || 1
        source ${working_dir}/bin/activate || 1

        ( cd $pycrypto_dir ; git checkout $pycrypto_version ) &>/dev/null
        ( cd $paramiko_dir ; git checkout $paramiko_version ) &>/dev/null
        pip install 'ecdsa<2.0,>=0.11' &> /dev/null || exit 1
        pip install ${pycrypto_dir} &>/dev/null || exit 1
        pip install -e ${paramiko_dir} &>/dev/null || exit 1

        echo "Testing with pycrypto==${pycrypto_version}, paramiko==${paramiko_version}"
        echo -n "Without patch: "
        ${test_exec}

        ( cd $paramiko_dir ; git cherry-pick 4752287a7379da61245087ee7e35635a4e42bb3f ) &>/dev/null
        echo -n "With patch   : "
        ${test_exec}
    done
done
```

Output:
```
Testing with pycrypto==v2.1.0, paramiko==v1.17.3
Without patch: 18:13:11 up  2:24,  0 users,  load average: 0.03, 0.05, 0.05
With patch   : 18:13:11 up  2:24,  0 users,  load average: 0.03, 0.05, 0.05
Testing with pycrypto==v2.1.0, paramiko==v1.18.1
Without patch: 18:13:20 up  2:24,  0 users,  load average: 0.11, 0.06, 0.05
With patch   : 18:13:20 up  2:24,  0 users,  load average: 0.11, 0.06, 0.05
Testing with pycrypto==v2.2, paramiko==v1.17.3
Without patch: 18:13:29 up  2:24,  0 users,  load average: 0.10, 0.06, 0.05
With patch   : 18:13:30 up  2:24,  0 users,  load average: 0.09, 0.06, 0.05
Testing with pycrypto==v2.2, paramiko==v1.18.1
Without patch: 18:13:38 up  2:25,  0 users,  load average: 0.08, 0.06, 0.05
With patch   : 18:13:39 up  2:25,  0 users,  load average: 0.08, 0.06, 0.05
Testing with pycrypto==v2.3, paramiko==v1.17.3
Without patch: 18:13:47 up  2:25,  0 users,  load average: 0.07, 0.06, 0.05
With patch   : 18:13:48 up  2:25,  0 users,  load average: 0.07, 0.06, 0.05
Testing with pycrypto==v2.3, paramiko==v1.18.1
Without patch: 18:13:57 up  2:25,  0 users,  load average: 0.06, 0.06, 0.05
With patch   : 18:13:58 up  2:25,  0 users,  load average: 0.06, 0.06, 0.05
Testing with pycrypto==v2.4.1, paramiko==v1.17.3
Without patch: 18:14:08 up  2:25,  0 users,  load average: 0.05, 0.05, 0.05
With patch   : 18:14:09 up  2:25,  0 users,  load average: 0.05, 0.05, 0.05
Testing with pycrypto==v2.4.1, paramiko==v1.18.1
Without patch: 18:14:20 up  2:25,  0 users,  load average: 0.04, 0.05, 0.05
With patch   : 18:14:21 up  2:25,  0 users,  load average: 0.04, 0.05, 0.05
Testing with pycrypto==v2.5, paramiko==v1.17.3
Without patch: 18:14:33 up  2:26,  0 users,  load average: 0.03, 0.05, 0.05
With patch   : 18:14:33 up  2:26,  0 users,  load average: 0.03, 0.05, 0.05
Testing with pycrypto==v2.5, paramiko==v1.18.1
Without patch: 18:14:45 up  2:26,  0 users,  load average: 0.03, 0.05, 0.05
With patch   : 18:14:46 up  2:26,  0 users,  load average: 0.03, 0.05, 0.05
Testing with pycrypto==v2.6, paramiko==v1.17.3
Without patch: 18:14:57 up  2:26,  0 users,  load average: 0.02, 0.04, 0.05
With patch   : 18:14:58 up  2:26,  0 users,  load average: 0.02, 0.04, 0.05
Testing with pycrypto==v2.6, paramiko==v1.18.1
Without patch: 18:15:09 up  2:26,  0 users,  load average: 0.02, 0.04, 0.05
With patch   : 18:15:10 up  2:26,  0 users,  load average: 0.02, 0.04, 0.05
Testing with pycrypto==v2.6.1, paramiko==v1.17.3
Without patch: 18:15:21 up  2:26,  0 users,  load average: 0.01, 0.04, 0.05
With patch   : 18:15:22 up  2:26,  0 users,  load average: 0.01, 0.04, 0.05
Testing with pycrypto==v2.6.1, paramiko==v1.18.1
Without patch: 18:15:33 up  2:27,  0 users,  load average: 0.01, 0.04, 0.05
With patch   : 18:15:34 up  2:27,  0 users,  load average: 0.01, 0.04, 0.05
Testing with pycrypto==master, paramiko==v1.17.3
Without patch: No handlers could be found for logger "paramiko.transport"
CTR mode needs counter parameter, not IV
With patch   : 18:15:46 up  2:27,  0 users,  load average: 0.01, 0.04, 0.05
Testing with pycrypto==master, paramiko==v1.18.1
Without patch: No handlers could be found for logger "paramiko.transport"
CTR mode needs counter parameter, not IV
With patch   : 18:16:06 up  2:27,  0 users,  load average: 0.01, 0.04, 0.05
```

**Comment by jmh045000** [comment]
I now have two branches, one based on 1.17 and one based on 1.18.  Do you want me to submit two PRs, one for each of those release series?

**Comment by ploxiln** [comment]
My guess is that he'll want a PR against 1.17, and he'll merge it up into 1.18 himself. You can actually change the "base branch" of this PR (from `paramiko:master` to `paramiko:1.17`) if you click the "Edit" button next to the title.

**Comment by ploxiln** [comment]
Well, nevermind, you'll need to create a new pull request anyway, because this one is from your master branch (rather than e.g. a topic branch), so it would be rather awkward to force-push a 1.17-based branch to your master branch.

Sorry for the noise ...

**Comment by jmh045000** [comment]
Yea, not sure why I made it from the master branch... lazy I guess?  I'll open one to 1.17 and reference this PR, and let the owner decide what to do ;)

**Comment by khenderick** [comment]
A new python-crypto also hit the Ubuntu repos: https://bugs.launchpad.net/ubuntu/+source/paramiko/+bug/1665565

**Comment by bitprophet** [comment]
I'm digging out my ticket backlog today, and just made myself a note to handle this & other high priority, low hanging fruit tickets tomorrow (Mondays are my official OSS days now thanks to my employer). Thanks to everyone tracking this & updating it, and apologies for the tardiness (been heads down on a private alpha of a related project I'm trying to make public ASAP).

**Comment by bitprophet** [comment]
Yea, the other PR against the 1.x lines is the right one to merge; this code is no longer extant in master as it reflects a post-2.0 world. Closing.

**Comment by guillaume-uH57J9** [comment]
Is there any known workaround for this? 

Thanks for the fix, unfortunately the updated packages are not available in my distribution yet
https://packages.debian.org/jessie/python-paramiko
https://packages.debian.org/stretch/python-paramiko

**Comment by mimi1vx** [comment]
is, apply fix to your installed paramiko or use more sane distribution :)
or  build own package with applied fix
https://wiki.debian.org/BuildingAPackage

**Comment by guillaume-uH57J9** [comment]
Fair enough, I applied the fix to my install and it avoids the error message. 
The connection still fails, will try to investigate as to why.

**Comment by blackduckx** [comment]
I opened a case @Redhat to get the fix included in RHEL6. I let you know when I have an update.

I hit this bug while upgrading salt-minion, that depends on python-crypto 2.6.1.

**Comment by ExaneServerTeam** [comment]
Updated rpm packages to fix this issue for RHEL6 / CENTOS6 are available at this place:
https://copr.fedorainfracloud.org/coprs/exane/python-paramiko/
https://copr-be.cloud.fedoraproject.org/results/exane/python-paramiko/epel-6-x86_64/00575813-python-paramiko/

**Comment by THEdavehogue** [comment]
I needed this, thank you. Not sure why it never got merged.

**Comment by ploxiln** [comment]
> since this is the one with all the discussion: noting explicitly that #889 has been merged into the 1.17 and 1.18 lines and will get a release today as 1.17.4 and 1.18.2.

(also not applicable to paramiko-2.x)

**Pull request closed without merging**
