### PR TITLE
Change  BestEncryption to BestAvailableEncryption

### PR DESCRIPTION
**Pull request by ibuler**
cryptography.hazmat.primitives.serialization has no class name BestEncryption

### CODE REVIEW

**Comment by bitprophet** [comment]
Unfortunately this will break things for anybody using Cryptography 1.4! :(

I would suggest using a try/except to 'cascade' this so it first tries `BestAvailableEncryption`, then falls back to `BestEncryption`. That should mean it works on either version of Cryptography. Thanks!

**Comment by bitprophet** [comment]
Note to self: we'll probably also want to tweak our `.travis.yml` so it has test matrix cells for different Cryptography versions...

**Comment by ibuler** [comment]
Add try except , but I see Cryptography have no version use BestEncryption after 1.0

**Comment by bitprophet** [comment]
Putting in 2.1 but it might be appropriate for a 2.0.x bugfix, depending. Will have to think about it when I get to it.

**Comment by ploxiln** [comment]
I think `BestEncryption` was always a typo. In cryptography-0.8 it was `BestAvailableEncryption` and in cryptography-0.7 neither existed as far as I can tell.

**Comment by ploxiln** [comment]
Found link in another issue :) https://github.com/pyca/cryptography/commit/199dc276cd1b45a799b511090b37237df49d68a3#diff-f567fb1e66bd7ded34d4717d684339b7R188

`BestEncryption` was never in a release, it was renamed in the same pull request it was introduced in

**Comment by bitprophet** [comment]
Huh, weird. And I no longer recall what gave me the impression re: 1.4.x.

**Comment by bitprophet** [comment]
Rolling into #741 / #912.

**Pull request closed without merging**
