### PR TITLE
Correct parameter size issue on 32-bit Python under Windows

### PR DESCRIPTION
**Pull request by stevecohen42**
See issue 658.  This is the promised pull request.

### CODE REVIEW

**Comment by stevecohen42** [comment]
No clue why this failed in the check with travis-ci. The modified code was not executed. I suspect a test-environment issue with the latest master.

**Comment by bitprophet** [comment]
I think this is obviated by the to-be-merged-soon #619, can you please confirm that? (cc @jaraco)

**Comment by jaraco** [comment]
Yes, that's right, @bitprophet

**Comment by bitprophet** [comment]
thanks @jaraco! (and - going to release that real soon now. maybe tonight if I get lucky :))

**Comment by stevecohen42** [comment]
Yep - my bad - I searched the issues and pull requests but somehow missed this one.

**Pull request closed without merging**
