### PR TITLE
Fix SECURITY_ATTRIBUTES.descriptor setter

### LINKED ISSUE #461: NameError: global name 'descriptor' is not defined
There is error if use in windows.
File _winapi.py:220

    @descriptor.setter
    def descriptor(self, value):
        self._descriptor = descriptor
        self.lpSecurityDescriptor = ctypes.addressof(descriptor)

Maybe must be so:

    @descriptor.setter
    def descriptor(self, value):
        self._descriptor = value
        self.lpSecurityDescriptor = ctypes.addressof(value)

### PR DESCRIPTION
**Pull request by ThiefMaster**
closes #461

### CODE REVIEW

**Comment by bitprophet** [comment]
Add a changelog entry and I'll merge! Thanks.

**Comment by ThiefMaster** [comment]
Which one is the current one? The ChangeLog* files in the root folder seem to be a *little* bit outdated.

**Comment by ThiefMaster** [comment]
@bitprophet: ping

**Comment by bitprophet** [comment]
@ThiefMaster sorry, holiday time is a bad time for updates :(

The file to update is `sites/www/changelog.rst` - add new entry to top, follow format & style of previous `:bug:` entries. Thanks!

**Comment by bitprophet** [comment]
See #488 now, but will credit, thanks!

**Pull request closed without merging**
