### PR TITLE
Add arcfour cipher support

### PR DESCRIPTION
**Pull request by coreywright**
Add `arcfour` alongside existing `arcfour128` and `arcfour256` cipher
support and add `arcfour` to preferred cipher list.

### CODE REVIEW

**Comment by coreywright** [comment]
feel free to close this PR because you feel `arcfour` is insecure or insist that i don't add it to the preferred cipher list.

i created this patch in case someone else has need for it as i recently encountered a few openssh daemon instances running on centos 5 that only supported arcfour (though that's contrary to its default cipher list and the default wasn't overridden by `Ciphers` in /etc/ssh/sshd_config) and generated `SSHException: Incompatible ssh server (no acceptable ciphers)`.

i added it to the preferred cipher list because i couldn't figure out how to add it at run-time *without* losing the convenience of `SSHClient`.  (i couldn't find a way to create a transport, start the connection, modify the security options, and hand-off the transport to a client so as to use the client's convenience functions, and doing all the aforementioned so as to create a channel to prime a client with (passing it into the client as `sock=`) didn't seen right (ie how would the client code properly close the transport if it only had the transport's potentially-just-one-of-many channel and operating on it using a socket interface, except by breaking the socket abstraction?), but maybe i'm too blind/stupid.)

i didn't add any tests because i searched for and didn't find anytests that referenced arcfour(128|256) (ie unit test(s) that cover the arcfour-related cipher-specific logic in `_get_cipher()`).

**Comment by bitprophet** [comment]
Thanks for the submission!

> i recently encountered a few openssh daemon instances running on centos 5 that only supported arcfour (though that's contrary to its default cipher list and the default wasn't overridden by Ciphers in /etc/ssh/sshd_config) and generated SSHException: Incompatible ssh server (no acceptable ciphers).

Were you able to confirm that they literally only run `arcfour` in their cipherlist and nothing else? E.g. via Python debug logging, or OpenSSH's client + `-v`? Seems unlikely to me - I'd wonder if it is some other missing cipher on our end instead, or a bug in the agreement handshaking.

I ask because I'm hoping the "real" solution here is some combo of adding a different cipher, and/or making it easier to shuffle around the ciphers/keys/etc lists (see eg the longstanding #50) so something else gets selected.

You're right that I'd _prefer_ not to add support for older, generally-considered-insecure cryptographic methods; part of "good security" is making it difficult to do bad security. That said, I also hate telling users with unusual but intractable use cases that they're wrong, especially when adding support to solve their issue is low-impact.

Also curious if others like @ploxiln or @lndbrg have suggestions or opinions.

**Comment by ploxiln** [comment]
I have no real expertise here, sorry :) It does seem like it would be better to make arcfour support an opt-in thing for people who need it for a special case.

**Comment by ploxiln** [comment]
On the other hand, it appears that "arcfour" is just another name for "arcfour128" which is already present, so it shouldn't really make the existing configuration worse.

**Comment by coreywright** [comment]
@bitprophet 

yes, i investigated the situation and added arcfour (as seen in this PR) as a last resort.  here are both openssh and paramiko client logs showing that the only cipher offered by the server is `arcfour`:

# openssh
```
$ ssh -vv root@www.xxx.yyy.zzz exit 2>&1 | grep kex
debug2: kex_parse_kexinit: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: kex_parse_kexinit: ssh-rsa-cert-v01@openssh.com,ssh-rsa-cert-v00@openssh.com,ssh-rsa,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-dss-cert-v00@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,ssh-dss
debug2: kex_parse_kexinit: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,arcfour256,arcfour128,3des-cbc,blowfish-cbc,cast128-cbc,arcfour
debug2: kex_parse_kexinit: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,arcfour256,arcfour128,3des-cbc,blowfish-cbc,cast128-cbc,arcfour
debug2: kex_parse_kexinit: hmac-sha1,umac-64@openssh.com,hmac-ripemd160,hmac-sha1-96
debug2: kex_parse_kexinit: hmac-sha1,umac-64@openssh.com,hmac-ripemd160,hmac-sha1-96
debug2: kex_parse_kexinit: zlib@openssh.com,zlib,none
debug2: kex_parse_kexinit: zlib@openssh.com,zlib,none
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: first_kex_follows 0 
debug2: kex_parse_kexinit: reserved 0 
debug2: kex_parse_kexinit: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: kex_parse_kexinit: ssh-rsa,ssh-dss
debug2: kex_parse_kexinit: arcfour
debug2: kex_parse_kexinit: arcfour
debug2: kex_parse_kexinit: hmac-md5,hmac-sha1,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: hmac-md5,hmac-sha1,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit: none,zlib@openssh.com
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: 
debug2: kex_parse_kexinit: first_kex_follows 0 
debug2: kex_parse_kexinit: reserved 0 
debug1: kex: server->client arcfour hmac-sha1 zlib@openssh.com
debug1: kex: client->server arcfour hmac-sha1 zlib@openssh.com
debug2: kex_derive_keys
```
# paramiko
note: Paramiko 2.1.1 from PyPI, but patched with this PR
```
$ venv/bin/python2 paramiko-debug.py www.xxx.yyy.zzz root 2>&1 | grep -E 'kex|agreed'
2017-03-06 21:52:35 CST 32153 DEBUG transport kex algos:[u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ssh-dss'] client encrypt:[u'arcfour'] server encrypt:[u'arcfour'] client mac:[u'hmac-md5', u'hmac-sha1', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5', u'hmac-sha1', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False _log /tmp/venv/local/lib/python2.7/site-packages/paramiko/transport.py:1574
2017-03-06 21:52:35 CST 32153 DEBUG transport Kex agreed: diffie-hellman-group1-sha1 _log /tmp/venv/local/lib/python2.7/site-packages/paramiko/transport.py:1574
2017-03-06 21:52:35 CST 32153 DEBUG transport Cipher agreed: arcfour _log /tmp/venv/local/lib/python2.7/site-packages/paramiko/transport.py:1574
2017-03-06 21:52:35 CST 32153 DEBUG transport MAC agreed: hmac-md5 _log /tmp/venv/local/lib/python2.7/site-packages/paramiko/transport.py:1574
2017-03-06 21:52:35 CST 32153 DEBUG transport Compression agreed: none _log /tmp/venv/local/lib/python2.7/site-packages/paramiko/transport.py:1574
2017-03-06 21:52:35 CST 32153 DEBUG transport kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1> _log /tmp/venv/local/lib/python2.7/site-packages/paramiko/transport.py:1574
```

i am baffled as to why this server only supports `arcfour` (as i examined /etc/ssh/sshd_config and there was no `Ciphers arcfour` configuration option overriding the default list of ciphers and know of other centos 5.7 servers with the same exact openssh packages with the same exact configuration file, but properly supporting the documented default ciphers), but i don't want this PR to get distracted by that fact (though feel free to close this PR stating that ssh servers only supporting `arcfour` are not supported).

the reason why i went through the effort of creating this PR was in response to my bewilderment that several versions of openssh (eg debian 7/8, ubuntu 14.04, though admittedly ubuntu 16.04 doesn't by default) could connect to the server, but paramiko couldn't, which was explained upon examination, seeing that only `arcfour` was supported by the server, and while the various openssh versions supported it, paramiko did not.

i would understand something like what's present in recent versions of openssh: arcfour is supported, but not by default; but supported-but-not-by-default is very difficult in the face of #50 (which succinctly describes what i tried to express in my original PR comment about why i added `arcfour` to the default cipher list).

**Comment by coreywright** [comment]
@ploxiln 

the difference between `arcfour` and `arcfour128` is slight but theoretically significant: technically the same cipher (ie algo, block & key size) but, in the case of `arcfour128` (and `arcfour256`) the first 1536 bytes are discarded because (if i understand correctly not having actually read mironov's paper) the algorithm, and perhaps even the key, can be discerned from the start of the rc4 stream (as compared to appearing as random bytes), so throwing away the start of the stream avoids that.

so the cipher is still supported by openssh (in the latest versions distributed with the linux distros i use), but not by default as it's superseded by equally fast (if only because of aes hardware acceleration), but less known flawed, ciphers.

**Comment by ploxiln** [comment]
Ah, I see that now (skipping the first 1536 rounds), thanks for the explanation.

**Comment by ploxiln** [comment]
Considering "arcfour" is still in the default allowed ciphers list of ssh (at the very end) (which can be confirmed with `man ssh_config`) it is probably OK for paramiko to have similar behavior. I would guess that the reasoning is that the host identity is confirmed with the host key, so it's ok to trust the ciphers list from sshd on the host, and leave the possibility of using arcfour up to sshd on the host . (The default ciphers list for sshd does not contain any variant of "arcfour".)

**Comment by ploxiln** [comment]
But on the other hand, this `_preferred_ciphers` list is also used for paramiko server side, and openssh will remove arcfour completely soon: http://www.openssh.com/txt/release-7.4

> We plan on retiring more legacy cryptography in future releases, specifically:
>
> * In approximately August 2017, removing remaining support for the
>   SSH v.1 protocol (client-only and currently compile-time disabled).
>
> * In the same release, removing support for Blowfish and RC4 ciphers
>   and the RIPE-MD160 HMAC. (These are currently run-time disabled).

¯\_(ツ)_/¯

**Comment by bitprophet** [comment]
Yup, it's not clear-cut; as noted, best practices is to remove such algorithms entirely, but OTOH it's still supported by current versions, and we in Paramiko land don't even have a clear policy around whether to mirror OpenSSH's feature _removals_ (only that we like to match them in terms of general behavior & new features when possible).

Feels to me like the best have-cake-and-eat-too solution is to consider this PR as conditional on #50 being solved: add `arcfour` for users with extenuating circumstances, _but_ ensure it is not in the default cipher list for unwitting users to accidentally end up using it - meaning it needs to be easier to update the contents of the used cipher/etc/etc lists when one truly needs to opt-in to it.

Given we've already mentioned #50 a bunch in here, the tickets are now linked. And while that ticket is old, I'd never labeled it or put it in a milestone, which I did yesterday - so it's back on the official radar (instead of just my disturbingly large mental todo list). I put it in 3.0 on assumption that implementing it would go hand-in-hand with changing the default lists, but it'd probably be equally easy for it to go into a 2.x feature release and save the list content change-up for 3.0.

**Comment by ploxiln** [comment]
this may be obsolete since #667 was just merged for 2.0+ (because arcfour ciphers were apparently never fully working in 2.0+)

**Comment by bitprophet** [comment]
Yea I'd forgotten about this discussion, apologies. And yes, for now, we've decided to simply axe arcfour from 2.0+, the folks I look to for Good Security Practices™ are pretty clear that RC4 is completely toast.

If/when we do get the "users can easily manage their own cipher lists" stuff worked out it's remotely possible we'll undo that change and add it back; hard to say.

**Pull request closed without merging**
